openapi: 3.0.3
info:
  title: AI-Powered Todo Chatbot API
  description: API for managing tasks through natural language conversations with an AI assistant
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/{user_id}/chat:
    post:
      summary: Send a message to the AI assistant
      description: Sends a user message to the AI assistant and receives a response along with any tool calls made
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user sending the message
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: integer
                  description: ID of the conversation (optional, creates new if not provided)
                  nullable: true
                message:
                  type: string
                  description: The user's message to the AI assistant
                  example: "Remind me to buy groceries"
              required:
                - message
      responses:
        '200':
          description: Successful response from the AI assistant
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: integer
                    description: ID of the conversation
                  response:
                    type: string
                    description: The AI assistant's response
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the tool called
                        arguments:
                          type: object
                          description: Arguments passed to the tool
                    description: List of tools called by the AI assistant
                required:
                  - conversation_id
                  - response
                  - tool_calls
        '400':
          description: Bad request due to invalid input
        '500':
          description: Internal server error
  /api/users/{user_id}/tasks:
    get:
      summary: List user's tasks
      description: Retrieves all tasks for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: string
        - name: status
          in: query
          required: false
          description: Filter tasks by status (all, pending, completed)
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '400':
          description: Invalid user ID or status parameter
        '500':
          description: Internal server error
    post:
      summary: Create a new task
      description: Creates a new task for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the task
                  example: "Buy groceries"
                description:
                  type: string
                  description: Detailed description of the task
                  example: "Milk, eggs, bread, fruits"
              required:
                - title
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
        '500':
          description: Internal server error
  /api/users/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Retrieves details of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Task details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error
    put:
      summary: Update a task
      description: Updates the details of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Updated title of the task
                description:
                  type: string
                  description: Updated description of the task
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '400':
          description: Invalid input data
        '500':
          description: Internal server error
    delete:
      summary: Delete a task
      description: Deletes a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error
  /api/users/{user_id}/tasks/{task_id}/complete:
    post:
      summary: Mark a task as completed
      description: Marks a specific task as completed
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to mark as completed
          schema:
            type: integer
      responses:
        '200':
          description: Task marked as completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the task
        user_id:
          type: string
          description: Identifier for the user who owns the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        completed:
          type: boolean
          description: Status indicating if the task is completed
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at